word_city = {
    "city_name_en": [
        "Amsterdam",
        "Athens",
        "Baghdad",
        "Bangkok",
        "Barcelona",
        "Beijing",
        "Belgrade",
        "Berlin",
        "Bogota",
        "Bratislava",
        "Brussels",
        "Bucharest",
        "Budapest",
        "Buenos Aires",
        "Cairo",
        "Cape Town",
        "Caracas",
        "Chicago",
        "Copenhagen",
        "Dhaka",
        "Dubai",
        "Dublin",
        "Frankfurt",
        "Geneva",
        "The Hague",
        "Hanoi",
        "Helsinki",
        "Hong Kong",
        "Istanbul",
        "Jakarta",
        "Jerusalem",
        "Johannesburg",
        "Kabul",
        "Karachi",
        "Kyiv",
        "Kuala Lumpur",
        "Lagos",
        "Lahore",
        "Lima",
        "Lisbon",
        "Ljubljana",
        "London",
        "Los Angeles",
        "Luxembourg",
        "Madrid",
    ],
    "city_name_ru": [
        "Амстердам",
        "Афины",
        "Багдад",
        "Бангкок",
        "Барселона",
        "Пекин",
        "Белград",
        "Берлин",
        "Богота",
        "Братислава",
        "Брюссель",
        "Бухарест",
        "Будапешт",
        "Буэнос-Айрес",
        "Каир",
        "Кейптаун",
        "Каракас",
        "Чикаго",
        "Копенгаген",
        "Дакка",
        "Дубай",
        "Дублин",
        "Франкфурт",
        "Женева",
        "Гаага",
        "Ханой",
        "Хельсинки",
        "Гонконг",
        "Стамбул",
        "Джакарта",
        "Иерусалим",
        "Йоханнесбург",
        "Кабул",
        "Карачи",
        "Киев",
        "Куала-Лумпур",
        "Лагос",
        "Лахор",
        "Лима",
        "Лиссабон",
        "Любляна",
        "Лондон",
        "Лос-Анджелес",
        "Люксембург",
        "Мадрид",
    ],
}
