# Generated by Django 5.0.3 on 2024-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weathercity",
            name="icons",
        ),
        migrations.AddField(
            model_name="weathercity",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="weathercity",
            name="icon",
            field=models.CharField(default=1, max_length=200, verbose_name="ID Icon"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weathercity",
            name="temp",
            field=models.IntegerField(null=True, verbose_name="Temperature"),
        ),
    ]
