# Generated by Django 5.0.4 on 2024-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name",
            field=models.CharField(default=1, max_length=150, verbose_name="City"),
            preserve_default=False,
        ),
    ]
